script:
  - true

env:
  matrix:
    - VARNISH_VERSION=4.1
    - VARNISH_VERSION=4.0
    - VARNISH_VERSION=3.0
build:
  pre_ci:
    docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag=mygento/varnish:$VARNISH_VERSION
  on_success:
    docker push mygento/varnish:$VARNISH_VERSION
