env:
  matrix:
    - VARNISH_VERSION='4.1'
    - VARNISH_VERSION='4.0'
    - VARNISH_VERSION='3.0'
build:
  pre_ci:
    - sed -i -e s/VARNISH_VERSION/${VARNISH_VERSION}/g module.yaml
    - docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag=mygento/varnish:$VARNISH_VERSION .
  pre_ci_boot:
    image_name: mygento/varnish
    image_tag: $VARNISH_VERSION
    pull: false
  ci:
      true
  on_success:
    docker push mygento/varnish:$VARNISH_VERSION

integrations:
    hub:
      - integrationName: Docker
        type: docker
