name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          # - trixie
          - bookworm
          # - lts
          # - fresh
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Test Ruby Version
        run: ruby -v
      - id: install_puppet
        name: Install Puppet
        continue-on-error: true
        run: |
          sudo apt-get -qqy install git sudo ruby
          sudo gem install puppet -v 7.27.0 --no-document
          sudo rm -fR /etc/puppetlabs/code/modules/image_build
          sudo git clone --single-branch --branch v2 https://github.com/luckyraul/puppetlabs-image_build.git /etc/puppetlabs/code/modules/image_build
      - name: Test Puppet Version
        run: puppet -V

      - name: Build Image
        run: |
          for arch in amd64 arm64 ; do
              sudo puppet docker build --image-name luckyraul/varnish:${{ matrix.version }}-$arch --no-show-diff --native --buildkit --platform linux/$arch --load
          done
      - name: Test Image Version Amd64
        run: docker run --rm luckyraul/varnish:${{ matrix.version }}-amd64 varnishd -V
      - name: Test Image Version Arm64
        run: docker run --rm luckyraul/varnish:${{ matrix.version }}-arm64 varnishd -V

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Retag Images
        run: |
          docker tag luckyraul/varnish:${{ matrix.version }}-amd64 ghcr.io/luckyraul/varnish:${{ matrix.version }}-amd64
          docker tag luckyraul/varnish:${{ matrix.version }}-arm64 ghcr.io/luckyraul/varnish:${{ matrix.version }}-arm64
      - name: Push Images
        run: |
          docker push ghcr.io/luckyraul/varnish:${{ matrix.version }}-amd64
          docker push ghcr.io/luckyraul/varnish:${{ matrix.version }}-arm64
      - name: Create Manifest
        run: |
          docker manifest create ghcr.io/luckyraul/varnish:${{ matrix.version }} --amend ghcr.io/luckyraul/varnish:${{ matrix.version }}-arm64 --amend ghcr.io/luckyraul/varnish:${{ matrix.version }}-amd64
          docker manifest push ghcr.io/luckyraul/varnish:${{ matrix.version }}
      - name: Retag Images Mygento
        run: |
          docker tag ghcr.io/luckyraul/varnish:${{ matrix.version }}-amd64 ghcr.io/mygento/varnish:${{ matrix.version }}-amd64
          docker tag ghcr.io/luckyraul/varnish:${{ matrix.version }}-arm64 ghcr.io/mygento/varnish:${{ matrix.version }}-arm64
      - name: Push Images Mygento
        run: |
          docker push ghcr.io/mygento/varnish:${{ matrix.version }}-amd64
          docker push ghcr.io/mygento/varnish:${{ matrix.version }}-arm64
      - name: Create Manifest Mygento
        run: |
          docker manifest create ghcr.io/mygento/varnish:${{ matrix.version }} --amend ghcr.io/mygento/varnish:${{ matrix.version }}-arm64 --amend ghcr.io/mygento/varnish:${{ matrix.version }}-amd64
          docker manifest push ghcr.io/mygento/varnish:${{ matrix.version }}
  post_build:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged ghcr LR
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ secrets.CR_PAT }}
          repository_owner: ${{ github.repository_owner }}
          owner_type: user
          package_name: varnish
      - name: Delete untagged ghcr Mygento
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ secrets.CR_PAT }}
          repository_owner: mygento
          owner_type: org
          package_name: varnish